name: "deploy Azure storage account"

on:
  push:
    branches: [ "main" ]
    paths-ignore: ["*.ps1", ".github/workflows/*"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter on Bicep file
        run: az bicep build --file storage.bicep